version: '3'
services:
  db:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.0.8-alpine
    ports:
      - 6379:6379
  web:
    build: .
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env.docker
      - .env.development
    environment:
      REDIS_URL: redis://redis:6379/1
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
volumes:
  postgres:
  bundle:
  node_modules:
