default: &default
  adapter: postgresql
  pool: 20
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: ocf_collab_development

test:
  <<: *default
  database: ocf_collab_test

production:
  <<: *default
  database: ocf_collab_production
